services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Ensure is loaded as a service.
    Wexample\SymfonyHelpers\:
        resource: '../../{Routing,Service}'
        tags: ['controller.service_arguments']

    Wexample\SymfonyHelpers\Form\EntityType:
        class: Wexample\SymfonyHelpers\Form\EntityType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type }

    Wexample\SymfonyHelpers\Form\EntitySearchType:
        class: Wexample\SymfonyHelpers\Form\EntitySearchType
        tags:
            - { name: form.type }

    Wexample\SymfonyHelpers\Routing\SimpleRoutesRouteLoader:
        arguments:
            $taggedControllers: !tagged_iterator 'has_simple_routes'
        tags:
            - { name: 'routing.loader' }

    Wexample\SymfonyHelpers\Service\ReversedRoleHierarchy:
        arguments: ['%security.role_hierarchy.roles%']
