services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Ensure is loaded as a service.
    Wexample\SymfonyHelpers\:
        resource: '../../{Routing,Service,Twig}'
        tags: ['controller.service_arguments']

    Wexample\SymfonyHelpers\Routing\SimpleRoutesRouteLoader:
        arguments:
            $container: '@service_container'
        tags:
            - { name: 'routing.loader' }

    Wexample\SymfonyHelpers\Service\ReversedRoleHierarchy:
        arguments: ['%security.role_hierarchy.roles%']

    Wexample\SymfonyHelpers\Service\Rectify\Rule\ImportDtoRule:
        tags:
            - { name: 'wexample.rectify.rule', priority: 105 }

    Wexample\SymfonyHelpers\Command\RectifyCommand: ~
